### PR TITLE
Fix update bugs, change server, untrack course database

### PR DESCRIPTION
**Pull request by davidschlachter**
Summary of changes:

- Fixed a bug in `getCourses.py` ('Next' button had moved on uOttawa site)
- Make number of workers configurable in `getTimetables.py` (default is still equal to the number of cores)
- Change default server to `schlachter.ca:5555` (automatically updates course schedules weekly)
- Change to Chromium webdriver in `getCourses.py`
- Untrack course databases

### CODE REVIEW

**Comment by morinted** [comment]
I can make you a contributor on this repo, and you can start making releases here if you are willing to take over.

When updating the courses, do you have a strategy to rerun and grab the skipped ones?

**Comment by davidschlachter** [comment]
I’d be happy to be a contributor.

When I update the timetables, I recurse over `getTimetables.py -s` until the output the same. Here’s my script: https://gist.github.com/davidschlachter/97e80e6e3881f91b5928005c80fea276

**Comment by morinted** [comment]
Looks like there are conflicts that GitHub doesn't like, maybe you can revise your history?

If you'd like to take over maintaining the repo, I'm almost done my uOttawa program and I'm not feeling the desire to continue. You can definitely add your name to the readme as part of the PR.

**Comment by morinted** [comment]
(Also, apologies for not replying sooner, amazing how easy it is to get disorganized when you don't make a TODO list!)

**Comment by davidschlachter** [comment]
Thanks! I'm happy to maintain it. I've resolved the conflicts and made a new release.

**Pull request merged**
