### PR TITLE
Fix SSL protocol error

### PR DESCRIPTION
**Pull request by davidschlachter**
Fixes issue #8 — need to specify TLSv1 (as opposed to TLS1.1 or 1.2) to connect to uOttawa timetables site now. I understand this is because of an OpenSSL update (https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/965371).

### CODE REVIEW

**Comment by morinted** [comment]
Ah, this is new, thanks...

Would you happen to be set up to create an update of the "database"? I haven't done it for months (and a busy schedule doesn't really encourage it)

Let me know,
Ted

**Comment by morinted** [comment]
Also, before I merge this, would you like to fix your commit so that it has an email address matching your GitHub account? If not, I will merge.

**Comment by davidschlachter** [comment]
Ah, thanks for catching that!

I’m doing a database update now and I’ll push it in a commit to this pull request.

**Comment by davidschlachter** [comment]
I’ve added a commit for the database update, and also added a tip to the Read Me for updating it without a graphical session.

**Comment by morinted** [comment]
Big thanks for reviving this... guess that means that I'll have to update my server. Cheers!

**Pull request merged**
